# Generated by Django 5.0.3 on 2024-03-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'pending'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
