# Generated by Django 5.0.3 on 2024-03-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_status'),
        ('restaurant', '0007_order_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='order',
        ),
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='restaurant.order'),
        ),
    ]
