# Generated by Django 5.0.3 on 2024-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_order_booking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
