# Generated by Django 5.0.3 on 2024-04-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_guest_name_guest_firstname_guest_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
