# Generated by Django 5.0.3 on 2024-04-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_guest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
    ]
