# Generated by Django 5.0.3 on 2024-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True),
        ),
    ]
