# Generated by Django 5.0.3 on 2024-04-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_reservation_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
