# Generated by Django 5.0.4 on 2024-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_reservation_date_created_reservedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedroom',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
