# Generated by Django 5.0.4 on 2024-04-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_reservedroom_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=12),
        ),
    ]
