# Generated by Django 5.0.4 on 2024-04-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_roomtype_images_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_occupancy',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='max_occupancy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
