# Generated by Django 5.0.4 on 2024-04-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_remove_room_amenities_remove_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=12),
        ),
    ]
