# Generated by Django 5.0.3 on 2024-03-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_order_items_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu_item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='restaurant.orderitem'),
        ),
    ]
