# Generated by Django 5.0.3 on 2024-03-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_orderitem_menu_item_price_remove_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('prepared', 'Prepared')], default='pending', max_length=12),
        ),
    ]
