# Generated by Django 5.0.3 on 2024-03-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_orderitem_order_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item_price',
        ),
    ]
