# Generated by Django 5.0.3 on 2024-03-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_orderitem_menu_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
