# Generated by Django 5.0.3 on 2024-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_order_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
