# Generated by Django 5.0.4 on 2024-04-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_orderitem_placed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='room',
        ),
    ]
