# Generated by Django 5.0.4 on 2024-04-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='images',
            field=models.ImageField(blank=True, upload_to='menu_images/'),
        ),
    ]
