# Generated by Django 5.0.4 on 2024-04-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_menuitem_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='today_special',
            field=models.BooleanField(default=False),
        ),
    ]
