# Generated by Django 5.0.4 on 2024-04-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_menuitem_today_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('prepared', 'Prepared'), ('delivered', 'Delivered')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('prepared', 'Prepared')], default='preparing', max_length=12),
        ),
    ]
