# Generated by Django 5.0.4 on 2024-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('prepared', 'Prepared'), ('delivered', 'Delivered')], default='preparing', max_length=12),
        ),
    ]
